name: Deploy to EC2

on:
  push:
    branches:
      - main        # Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, mysql
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /var/www/html/restrovibe_backend
            
            # Pull latest code
            git pull origin main
            
            # Install/update dependencies
            composer install --no-dev --optimize-autoloader
            
            # Run migrations
            php artisan migrate
            
            # Clear and cache config
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Set permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            # Restart PHP-FPM (optional but recommended)
            sudo systemctl restart php8.3-fpm
